#!/usr/bin/env python3
"""
stage4_digest.py — Morning digest email of ready applications
──────────────────────────────────────────────────────────────
What it does:
  1. Fetches all "Resume Tailored" jobs from Notion (not yet applied)
  2. Generates a clean HTML digest with a table + action suggestions
  3. Prints digest to terminal (copy/paste to email)
  4. Optionally sends via Gmail if credentials are configured

Run:  python scripts/stage4_digest.py
      python scripts/stage4_digest.py --send   (send via Gmail)
"""

import sys, datetime
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from config.settings import *
from scripts.utils import claude_chat, db_get_ready_to_apply, db_get_jobs, log, today


# ── Build digest content ──────────────────────────────────────

def action_suggestion(job: dict) -> str:
    score = job.get("ats", 0)
    if score >= 80:
        return "🔥 High match — apply directly today"
    elif score >= 60:
        return "✅ Good match — apply + send warm outreach if possible"
    elif score >= 40:
        return "🟡 Moderate — apply, consider adjacent role angle"
    else:
        return "⚪ Lower match — apply to adjacent roles first"


def build_html_digest(jobs: list) -> str:
    """Ready-to-apply digest — jobs with tailored resumes."""
    date_str = datetime.date.today().strftime("%B %d, %Y")
    rows = ""
    for job in jobs:
        action = action_suggestion(job)
        resume_link = job.get("resume_link") or "—"
        resume_cell = f'<a href="{resume_link}">View resume</a>' if resume_link != "—" else "—"
        rows += f"""
        <tr>
          <td>{job['company']}</td>
          <td>{job['title']}</td>
          <td>{job.get('location') or '—'}</td>
          <td style="text-align:center"><strong>{int(job.get('ats', 0))}</strong></td>
          <td>{resume_cell}</td>
          <td style="font-size:12px;color:#555">{action}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: -apple-system, sans-serif; color: #1a1a1a; max-width: 720px; margin: 0 auto; padding: 20px; }}
  h2 {{ color: #1a1a1a; border-bottom: 1px solid #eee; padding-bottom: 8px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
  th {{ background: #f4f4f4; text-align: left; padding: 8px 10px; font-size: 13px; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #f0f0f0; font-size: 13px; vertical-align: top; }}
  tr:hover td {{ background: #fafafa; }}
  .footer {{ margin-top: 24px; font-size: 12px; color: #888; }}
</style>
</head>
<body>
  <h2>📋 Job Applications Ready — {date_str}</h2>
  <p style="color:#555;font-size:13px">{len(jobs)} resume(s) tailored and ready to apply. Sorted by ATS match score.</p>
  <table>
    <thead>
      <tr>
        <th>Company</th>
        <th>Role</th>
        <th>Location</th>
        <th style="text-align:center">ATS</th>
        <th>Resume</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <p class="footer">
    📊 <a href="https://www.notion.so/{NOTION_DB_ID.replace('-','')}">Open full tracker in Notion</a>
    &nbsp;·&nbsp; Generated by your AI Job Search pipeline
  </p>
</body>
</html>"""


def build_html_review_digest(jobs: list) -> str:
    """Review digest — all freshly scraped jobs, before tailoring. User marks Reviewed here."""
    date_str = datetime.date.today().strftime("%B %d, %Y")
    rows = ""
    for job in jobs:
        score = int(job.get("ats_score", 0))
        if score >= 80:
            badge = "🔥"
        elif score >= 60:
            badge = "✅"
        elif score >= 40:
            badge = "🟡"
        else:
            badge = "⚪"
        rows += f"""
        <tr>
          <td>{job['company']}</td>
          <td>{job['title']}</td>
          <td>{job.get('location') or '—'}</td>
          <td style="text-align:center"><strong>{score}</strong> {badge}</td>
          <td><a href="{job.get('url','#')}">View posting</a></td>
        </tr>"""

    notion_url = f"https://www.notion.so/{NOTION_DB_ID.replace('-','')}"
    return f"""<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: -apple-system, sans-serif; color: #1a1a1a; max-width: 720px; margin: 0 auto; padding: 20px; }}
  h2 {{ color: #1a1a1a; border-bottom: 1px solid #eee; padding-bottom: 8px; }}
  .notice {{ background:#fff8e1; border-left:4px solid #f4a22d; padding:12px 16px; border-radius:4px; font-size:13px; margin-bottom:16px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
  th {{ background: #f4f4f4; text-align: left; padding: 8px 10px; font-size: 13px; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #f0f0f0; font-size: 13px; vertical-align: top; }}
  tr:hover td {{ background: #fafafa; }}
  .footer {{ margin-top: 24px; font-size: 12px; color: #888; }}
  code {{ background:#f4f4f4; padding:2px 6px; border-radius:3px; }}
</style>
</head>
<body>
  <h2>🔍 New Jobs Scraped — {date_str}</h2>
  <div class="notice">
    <strong>Action required:</strong> Review these {len(jobs)} jobs below.<br>
    Open <a href="{notion_url}">Notion</a> and set <strong>Status = Reviewed</strong> on jobs you want to apply to.<br>
    Then run <code>python run.py --evaluate</code> to tailor resumes for those jobs.
  </div>
  <table>
    <thead>
      <tr>
        <th>Company</th>
        <th>Role</th>
        <th>Location</th>
        <th style="text-align:center">ATS</th>
        <th>Posting</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <p class="footer">
    📊 <a href="{notion_url}">Open full tracker in Notion</a>
    &nbsp;·&nbsp; Generated by your AI Job Search pipeline
  </p>
</body>
</html>"""


def build_plain_digest(jobs: list) -> str:
    date_str = datetime.date.today().strftime("%B %d, %Y")
    lines = [f"JOB APPLICATIONS READY — {date_str}", "=" * 50, ""]
    for job in jobs:
        lines.append(f"  {job['company']} — {job['title']}")
        lines.append(f"    Location:     {job.get('location') or '—'}")
        lines.append(f"    ATS Score:    {int(job.get('ats', 0))}")
        lines.append(f"    Resume:       {job.get('resume_link', '—')}")
        lines.append(f"    Job URL:      {job.get('url', '—')}")
        lines.append(f"    Action:       {action_suggestion(job)}")
        lines.append("")
    lines.append(f"Notion Tracker: https://www.notion.so/{NOTION_DB_ID.replace('-','')}")
    return "\n".join(lines)


def build_plain_review_digest(jobs: list) -> str:
    date_str = datetime.date.today().strftime("%B %d, %Y")
    lines = [f"NEW JOBS SCRAPED — REVIEW REQUIRED — {date_str}", "=" * 50, ""]
    lines.append("  Open Notion and set Status = Reviewed on jobs you want to apply to.")
    lines.append("  Then run: python run.py --evaluate")
    lines.append("")
    for job in jobs:
        lines.append(f"  {job['company']} — {job['title']}")
        lines.append(f"    Location:  {job.get('location') or '—'}")
        lines.append(f"    ATS Score: {int(job.get('ats_score', 0))}")
        lines.append(f"    URL:       {job.get('url', '—')}")
        lines.append("")
    lines.append(f"Notion Tracker: https://www.notion.so/{NOTION_DB_ID.replace('-','')}")
    return "\n".join(lines)


# ── Optional: send via Gmail ──────────────────────────────────

def send_via_gmail(html: str, plain: str, subject: str = None):
    try:
        import base64
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build

        creds = Credentials.from_authorized_user_file(GMAIL_CREDENTIALS_PATH)
        service = build("gmail", "v1", credentials=creds)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject or f"Job applications ready — {today()}"
        msg["From"]    = YOUR_EMAIL
        msg["To"]      = DIGEST_RECIPIENT_EMAIL
        msg.attach(MIMEText(plain, "plain"))
        msg.attach(MIMEText(html,  "html"))

        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
        service.users().messages().send(userId="me", body={"raw": raw}).execute()
        log(f"✓ Digest sent to {DIGEST_RECIPIENT_EMAIL}")
    except ImportError:
        log("Gmail send requires: pip install google-auth google-auth-oauthlib google-api-python-client")
    except Exception as e:
        log(f"✗ Gmail send failed: {e}")
        log("Digest printed to terminal above.")


# ── Main ──────────────────────────────────────────────────────

def run(send: bool = False, mode: str = "ready"):
    """
    mode="ready"   — ready-to-apply digest (Resume Tailored jobs, default)
    mode="scraped" — review digest (all Scraped jobs, shown before tailoring)
    """
    if mode == "scraped":
        jobs = db_get_jobs(status="Scraped", min_score=0)
        if not jobs:
            log("No new scraped jobs to review.")
            return
        jobs_sorted = sorted(jobs, key=lambda x: x.get("ats_score", 0), reverse=True)
        html  = build_html_review_digest(jobs_sorted)
        plain = build_plain_review_digest(jobs_sorted)
        filename = f"review_digest_{today()}.html"
        subject  = f"Review new jobs — {today()} ({len(jobs_sorted)} scraped)"
    else:
        jobs = db_get_ready_to_apply()
        if not jobs:
            log("No jobs ready to apply. Run --evaluate first.")
            return
        jobs_sorted = sorted(jobs, key=lambda x: x.get("ats", 0), reverse=True)
        html  = build_html_digest(jobs_sorted)
        plain = build_plain_digest(jobs_sorted)
        filename = f"digest_{today()}.html"
        subject  = f"Job applications ready — {today()}"

    print("\n" + plain)

    out = Path(OUTPUT_DIR) / filename
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    log(f"\nHTML digest saved: {out}")

    if send:
        send_via_gmail(html, plain, subject=subject)
    else:
        log("To send via Gmail add --send")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--send", action="store_true", help="Send digest via Gmail")
    parser.add_argument("--mode", choices=["ready", "scraped"], default="ready",
                        help="'ready' = tailored jobs digest (default); 'scraped' = review digest")
    args = parser.parse_args()
    run(send=args.send, mode=args.mode)
